import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar, {
  ExternalNavLinkType,
  InternalNavLinkType,
} from "@/components/NavBar";
import ContextProvider from "@/components/contexts/ContextProvider";
import React from "react";
import { TbBrandGithub, TbBrandLinkedin, TbMail } from "react-icons/tb";
import { IoWarningOutline } from "react-icons/io5";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const internalNavLinks: InternalNavLinkType[] = [
    // {
    //   name: "Projects",
    //   href: "/projects",
    // },
    // {
    //   name: "Blogs",
    //   href: "/blogs",
    // },
    // {
    //   name: "Experience",
    //   href: "/experience",
    // },
  ];

  const externalNavLinks: ExternalNavLinkType[] = [
    {
      href: "https://github.com/marqsw",
      icon: <TbBrandGithub />,
    },
    {
      href: "https://www.linkedin.com/in/marquis-wong-80217b2ba",
      icon: <TbBrandLinkedin />,
    },
    {
      href: "mailto:marqsw@gmail.com",
      icon: <TbMail />,
    },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative m-5 flex flex-col antialiased`}
      >
        <ContextProvider>
          <NavBar
            internalNavLinks={internalNavLinks}
            externalNavLinks={externalNavLinks}
          />
          <div
            className={"mx-10 min-h-screen w-screen max-w-3xl self-center p-10"}
          >
            <div className="glassy-warning flex flex-row items-center gap-2 rounded-xl px-5 py-3 text-sm">
              <IoWarningOutline /> I am a new site and still in development!
              More content coming soon.
            </div>

            {children}
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
